# ./.tmuxinator.yml
<%
  branch = `git rev-parse --abbrev-ref HEAD`.strip
  safe_branch = branch.gsub(/[\/_]/, '-').downcase.gsub(/[^a-z0-9-]/, '')
  safe_schema = branch.gsub(/[\/-]/, '_').downcase.gsub(/[^a-z0-9_]/, '')
  if branch == "main"
    safe_schema = "public"
  elsif safe_schema =~ /^[0-9]/
    safe_schema = "_#{safe_schema}"
  end
%>

name: ourplaces

env:
  SERVICE_SUFFIX: <%= safe_branch %>
  SCHEMA_NAME: <%= safe_schema %>
  GCS_RAW_BUCKET: our-places-gcs-img-raw-<%= safe_branch %>
  GCS_PUBLIC_BUCKET: our-places-gcs-img-public-<%= safe_branch %>

enable_pane_titles: true

windows:
  - development:
      layout: "181x55,0,0{122x55,0,0[122x16,0,0{59x16,0,0,1,62x16,60,0,6},122x11,0,17,2,122x13,0,29,3,122x12,0,43,4],58x55,123,0[58x27,123,0,5,58x27,123,28,8]}"
      panes:
        - web_app:
          - cd web_app && ./run_local.sh    # Pane 1: Top-Left (Left column, row 1, left split)
        - web_app_admin:
          - cd web_app_admin && ./run_local.sh    # Pane 2: Top-Right (Left column, row 1, right split)
        - listing_api:
          - docker compose up -d db
          - cd app_api/listing_api
          - ./run_local.sh    # Pane 3: Left column, row 2
        - booking_api:
          - cd app_api/booking_api
          - ./run_local.sh    # Pane 4: Left column, row 3
        - user_api:
          - cd app_api/user_api
          - ./run_local.sh    # Pane 5: Left column, row 4
        - web_app_tailwind:
          - cd web_app && npx tailwindcss -i ./style/tailwind.css -o ./style/output.css --watch   # Pane 6: Right column, top half
        - web_app_admin_tailwind:
          - cd web_app_admin && npx tailwindcss -i ./style/tailwind.css -o ./style/output.css --watch    # Pane 7: Right column, bottom half


