[package]
name = "email_worker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["full"] }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing-actix-web.workspace = true
tracing-log.workspace = true

db_core.workspace = true
api_core.workspace = true
common.workspace = true
actix-web.workspace = true
base64 = "0.23.1"
serde_json.workspace = true
uuid.workspace = true
sqlx.workspace = true
async-trait = "0.1.89"
lettre = { version = "0.11", default-features = false, features = ["tokio1-rustls-tls", "smtp-transport", "builder"] }
rustls = { version = "0.23", features = ["ring"] }

[dev-dependencies]
dotenvy.workspace = true
sqlx-db-tester = { version = "0.7.1", default-features = false, features = [
    "postgres",
] }
actix-http = "3.13.6"
