# Use the official Rust image.
# https://hub.docker.com/_/rust
# syntax=docker/dockerfile:1
FROM gcr.io/distroless/cc
ARG BUILD_OUTPUT=debug
ARG POSTGRES_USER_ARG
ARG POSTGRES_PASSWORD_ARG
ARG POSTGRES_DB_ARG
ARG POSTGRES_HOST_ARG


WORKDIR /usr/src/app

COPY ./target/out/our-places-app-api-rs/${BUILD_OUTPUT} .
COPY ./config config
COPY ./log4rs.yml log4rs.yml

# Service must listen to $PORT environment variable.
# This default value facilitates local development.
# ENV PORT 8080
# ENV HOST 0.0.0.0
ENV RUN_ENV Development
ENV EA__DATABASE__USERNAME ${POSTGRES_USER_ARG}
ENV EA__DATABASE__PASSWORD ${POSTGRES_PASSWORD_ARG}
ENV EA__DATABASE__PORT 5432
ENV EA__DATABASE__HOST ${POSTGRES_HOST_ARG}
ENV EA__DATABASE__DATABASE_NAME ${POSTGRES_DB_ARG}

ENV EA__LOG__LEVEL Debug

# EXPOSE 8080

# Run the web service on container startup.
CMD ["./our-places-app-api-rs"]
