# Use the official Rust image.
# https://hub.docker.com/_/rust
# syntax=docker/dockerfile:1
FROM gcr.io/distroless/cc
ARG BUILD_TYPE=release
ARG BUILD_OUTPUT=release
ARG BUILD_OUTPUT
ARG POSTGRES_USER_ARG
ARG POSTGRES_PASSWORD_ARG
ARG POSTGRES_DB_ARG
ARG POSTGRES_HOST_ARG

ENV POSTGRES_USER=$POSTGRES_USER_ARG
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD_ARG
ENV POSTGRES_DB=$POSTGRES_DB_ARG
ENV POSTGRES_HOST=$POSTGRES_HOST_ARG

WORKDIR /usr/src/app

COPY ./target/out/our-places-app-api-rs/${BUILD_OUTPUT} .
COPY ./config config
COPY ./log4rs.yml log4rs.yml

# Service must listen to $PORT environment variable.
# This default value facilitates local development.
# ENV PORT 8080
# ENV HOST 0.0.0.0
# ENV RUN_ENV Development

# EXPOSE 8080

# Run the web service on container startup.
CMD ["./our-places-app-api-rs"]
