apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: us-central1-docker.pkg.dev/our-places-dev/cloud-run-source-deploy/our-places-rs
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-central1
  name: our-places-rs
  namespace: '689343985534'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        client.knative.dev/user-image: us-central1-docker.pkg.dev/our-places-dev/cloud-run-source-deploy/our-places-rs
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 407.0.0
      name: our-places-rs-00011-vod
    spec:
      containerConcurrency: 80
      containers:
      - image: us-central1-docker.pkg.dev/our-places-dev/cloud-run-source-deploy/our-places-rs@sha256:db96e062f8fc3ea7269f86eb7b839bee619c4272146b82b8150b51ad892e97d1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
      serviceAccountName: 689343985534-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
