CREATE TYPE email_status AS ENUM ('pending', 'processing', 'sent', 'failed');

CREATE TABLE email_outbox (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recipient_email VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    template_id VARCHAR(100) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    status email_status NOT NULL DEFAULT 'pending',
    attempts INT NOT NULL DEFAULT 0,
    max_retries INT NOT NULL DEFAULT 3,
    last_error TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for efficient querying and status auditing
CREATE INDEX idx_email_outbox_status_created ON email_outbox (status, created_at DESC);
CREATE INDEX idx_email_outbox_recipient ON email_outbox (recipient_email);

DO $$
BEGIN
    -- Only install pg_cron in the main database, as test DBs generated by sqlx-db-tester
    -- cannot support pg_cron (it is restricted to the DB named in cron.database_name).
    IF current_database() NOT LIKE '%test%' THEN
        BEGIN
            PERFORM cron.schedule('cleanup_sent_email_outbox', '0 3 * * *',
                'DELETE FROM email_outbox WHERE status = ''sent'' AND created_at < NOW() - INTERVAL ''30 days'';'
            );
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Skipping pg_cron setup for email_outbox cleanup: %', SQLERRM;
        END;
    END IF;
END
$$;
