DO $$
BEGIN
    -- Only install pg_cron in the main database, as test DBs generated by sqlx-db-tester
    -- cannot support pg_cron (it is restricted to the DB named in cron.database_name).
    IF current_database() NOT LIKE '%test%' THEN
        EXECUTE 'CREATE EXTENSION IF NOT EXISTS pg_cron;';
        
        PERFORM cron.schedule('cleanup_stale_pending_holds', '*/15 * * * *', 
            'WITH expired_bookings AS (
                UPDATE booking
                SET status = ''cancelled'', updated_at = NOW()
                WHERE status = ''pending'' 
                  AND created_at < NOW() - INTERVAL ''15 minutes''
                RETURNING *
            )
            INSERT INTO booking_history (
                booking_id, confirmation_code, guest_id, listing_id, status,
                date_from, date_to, currency, daily_rate, number_of_persons, total_days,
                sub_total_price, discount_value, tax_value, fee_breakdown, total_price,
                cancellation_policy, metadata, change_reason, created_at
            )
            SELECT 
                id, confirmation_code, guest_id, listing_id, status,
                date_from, date_to, currency, daily_rate, number_of_persons, total_days,
                sub_total_price, discount_value, tax_value, fee_breakdown, total_price,
                cancellation_policy, metadata, ''Hold expired after 15 minutes'', NOW()
            FROM expired_bookings;'
        );
    END IF;
END
$$;
