[server]
host = "0.0.0.0"
port = "8080"

[log]
level = "info"

[database]
username = "postgres"
password = "password"
port = "5432"
host = "localhost"
database_name = "our_places"
cloud = false
instance_name = ""

env = "Development"

[application]
max_attempts = 5

[feature_flags]
enable_hard_deletes = false
