[package]
name = "web_app_admin_tc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "web_app_admin_tc"
path = "src/main.rs"

[dependencies]
topcoat = { workspace = true, features = ["htmx", "tailwind"] }
web_app_common_tc = { workspace = true }
common = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
dotenvy = { workspace = true }

[build-dependencies]
topcoat = { version = "0.6.2", default-features = false, features = ["tailwind"] }
