[advisories]
ignore = [
    "RUSTSEC-2023-0071", # rsa / sqlx-mysql: Marvin Attack (No fixed upgrade available upstream)
    "RUSTSEC-2026-0235", # rkyv / rust_decimal: Insufficient archive validation
    "RUSTSEC-2025-0052", # async-std unmaintained warning
    "RUSTSEC-2024-0436", # paste unmaintained warning
    "RUSTSEC-2026-0173", # proc-macro-error2 unmaintained warning
]
