[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
uuid = { workspace = true, features = ["js"] }
chrono = { workspace = true }
rust_decimal = { workspace = true }
utoipa = { version = "6.0.0", features = ["uuid", "chrono", "decimal"] }
reqwest = { workspace = true }
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
validator = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
google-cloud-storage = { workspace = true }
google-cloud-auth = "1.6.0"
