[server]
host = "0.0.0.0"
port = "8080"

[log]
level = "info"

[database]
username = "postgres"
password = "password"
port = "5432"
host = "localhost"
database_name = "ourplaces_db"
cloud = "NO"
instance_name = ""
