@startuml
skinparam componentStyle uml2
skinparam backgroundColor white
skinparam component {
  BackgroundColor lightblue
  BorderColor darkblue
}

[web_app] as WA <<Leptos Web App>>
[web_app_admin] as WAA <<Leptos Admin App>>

package "app_api" {
    [api_core] as AC <<API Infrastructure>>
    [booking_api] as BA <<Service>>
    [image_worker] as IW <<Service>>
    [listing_api] as LA <<Service>>
    [user_api] as UA <<Service>>
}

[db_core] as DC <<Database Access>>
[web_app_common] as WAC <<Shared Common>>

' Frontends usage of common
WA ..> WAC : <<shared>>
WAA ..> WAC : <<shared>>

' Frontends usage of core (SSR)
WA ..> AC
WA ..> DC
WAA ..> AC
WAA ..> DC

' API dependencies
BA ..> AC
BA ..> DC
IW ..> AC
IW ..> DC
LA ..> AC
LA ..> DC
UA ..> AC
UA ..> DC

AC ..> DC

@enduml