name: CI/CD for app_api
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: our-places-app-api-rs
  REGION: us-central1
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - app_api/**
      - .github/workflows/cicd_app_api.yml

jobs:
  audit:
    name: Audit
    defaults:
      run:
        working-directory: ./app_api

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true
      - run: cargo audit

  lint_check:
    defaults:
      run:
        working-directory: ./app_api

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path app_api/Cargo.toml


  test:
    runs-on: ubuntu-latest
    if: 1 == 0

    defaults:
      run:
        working-directory: ./app_api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build
        run: cargo build --verbose
      
      - name: Run API tests
        run: cargo test --verbose

  
  build-and-deploy:
    runs-on: ubuntu-latest
    # needs: [test, lint_check, audit]

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container (release)
        working-directory: ./app_api
        if: github.ref == 'refs/heads/main'
        run: |-
          docker build --build-arg BUILD_TYPE=release --build-arg BUILD_OUTPUT=release -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Build and Push Container (dev)
        working-directory: ./app_api
        if: github.ref != 'refs/heads/main'
        run: |-
          docker build --build-arg BUILD_TYPE=dev --build-arg BUILD_OUTPUT=debug -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
        
      - name: Deploy to Cloud Run
        working-directory: ./app_api
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} \
            --platform "managed" \
            --allow-unauthenticated \
            --max-instances 1 \
            --memory 256Mi \
            --quiet