name: CI/CD for app_api
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GAR_REPO: our-places-repo
  REGION: us-central1
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - app_api/**
      - .github/workflows/cicd_app_api.yml

jobs:
  audit:
    name: Audit
    defaults:
      run:
        working-directory: ./app_api

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true
      - run: cargo audit

  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true

      - uses: actions-rs/clippy-check@v1
        env:
          RUN_ENV: Development
          DATABASE_URL: postgres://${{ vars.POSTGRES_BUILD_USER }}:${{ secrets.POSTGRES_BUILD_PASSWORD }}@${{ vars.POSTGRES_BUILD_HOST }}:5432/${{ vars.POSTGRES_BUILD_DB }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path Cargo.toml


  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Install sqlx (needed for compilation and integration tests)
        run: |-
          sudo apt-get install libpq-dev -y
          cargo install --version=~0.7 sqlx-cli --no-default-features --features rustls,postgres --force

      - name: Build Postgres container image (necessary for sqlx). Choose a random project to use
        run: cargo make --cwd app_api/listing_api prepare
      
      - name: Build app
        if: github.ref == 'refs/heads/dev'
        env:
          RUN_ENV: Development
          DATABASE_URL: postgres://${{ vars.POSTGRES_BUILD_USER }}:${{ secrets.POSTGRES_BUILD_PASSWORD }}@${{ vars.POSTGRES_BUILD_HOST }}:5432/${{ vars.POSTGRES_BUILD_DB }}
        run: cargo build --verbose
      
      - name: Run API tests
        if: github.ref == 'refs/heads/dev'
        env:
          RUN_ENV: Development
          DATABASE_URL: postgres://${{ vars.POSTGRES_BUILD_USER }}:${{ secrets.POSTGRES_BUILD_PASSWORD }}@${{ vars.POSTGRES_BUILD_HOST }}:5432/${{ vars.POSTGRES_BUILD_DB }}
        run: cargo test --verbose

  
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [audit, lint_check, test]
    
    defaults:
      run:
        working-directory: ./app_api

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set Build Arguments
        id: build_args
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "RELEASE_FLAG=--release" >> $GITHUB_ENV
            echo "BUILD_OUTPUT=release" >> $GITHUB_ENV
          else
            echo "RELEASE_FLAG=" >> $GITHUB_ENV
            echo "BUILD_OUTPUT=debug" >> $GITHUB_ENV
          fi

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Install sqlx (needed for compilation)
        run: |-
          sudo apt-get install libpq-dev -y
          cargo install --version=~0.7 sqlx-cli --no-default-features --features rustls,postgres --force

      - name: Install psql client (needed to see if Postgres is running)
        run: |-
          sudo apt-get install -y postgresql-client

      - name: Build Postgres container image (necessary for sqlx)
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_BUILD_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_BUILD_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_BUILD_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_BUILD_HOST }}
        run: cargo make docker-db-build
      
      - name: Run PostgreSQL image in a container (necessary for sqlx)
        run: cargo make docker-db-run

      - name: Run database migrations (necessary for sqlx)
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_BUILD_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_BUILD_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_BUILD_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_BUILD_HOST }}
        run: |-
          SKIP_DOCKER=true cargo make run-db-migrations

      # ---------------------------------------------------------
      # Booking API
      # ---------------------------------------------------------
      - name: Build and Push Booking API
        run: |
          docker build \
            --build-arg RELEASE_FLAG=${{ env.RELEASE_FLAG }} \
            --build-arg BUILD_OUTPUT=${{ env.BUILD_OUTPUT }} \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/booking-api:${{ github.sha }} \
            -f Dockerfile.booking_api .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/booking-api:${{ github.sha }}

      - name: Deploy Booking API
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: booking-api
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/booking-api:${{ github.sha }}
          region: ${{ env.REGION }}
          env_vars: |
            RUST_LOG=info
          flags: '--no-allow-unauthenticated --min-instances=0 --max-instances=1 --memory=256Mi --add-cloudsql-instances=${{ env.PROJECT_ID }}:${{ env.REGION }}:our-places-db-dev --quiet'

      # ---------------------------------------------------------
      # Listing API
      # ---------------------------------------------------------
      - name: Build and Push Listing API
        run: |
          docker build \
            --build-arg RELEASE_FLAG=${{ env.RELEASE_FLAG }} \
            --build-arg BUILD_OUTPUT=${{ env.BUILD_OUTPUT }} \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/listing-api:${{ github.sha }} \
            -f Dockerfile.listing_api .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/listing-api:${{ github.sha }}

      - name: Deploy Listing API
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: listing-api
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/listing-api:${{ github.sha }}
          region: ${{ env.REGION }}
          env_vars: |
            RUST_LOG=info
          flags: '--no-allow-unauthenticated --min-instances=0 --max-instances=1 --memory=256Mi --add-cloudsql-instances=${{ env.PROJECT_ID }}:${{ env.REGION }}:our-places-db-dev --quiet'

      # ---------------------------------------------------------
      # User API
      # ---------------------------------------------------------
      - name: Build and Push User API
        run: |
          docker build \
            --build-arg RELEASE_FLAG=${{ env.RELEASE_FLAG }} \
            --build-arg BUILD_OUTPUT=${{ env.BUILD_OUTPUT }} \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/user-api:${{ github.sha }} \
            -f Dockerfile.user_api .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/user-api:${{ github.sha }}

      - name: Deploy User API
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: user-api
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/user-api:${{ github.sha }}
          region: ${{ env.REGION }}
          env_vars: |
            RUST_LOG=info
          flags: '--no-allow-unauthenticated --min-instances=0 --max-instances=1 --memory=256Mi --add-cloudsql-instances=${{ env.PROJECT_ID }}:${{ env.REGION }}:our-places-db-dev --quiet'

  automated-api-tests:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI

        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests

        # Runs the sanity check collection using the postman-sanity-checks-api-key
        run: |
          postman collection run "701056-bf0597d5-23ee-4374-97f7-c3741a532c3f" -e "701056-4394872e-dc91-4235-8461-cf429a72769e"
