name: CI/CD for web_app

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GAR_REPO: our-places-repo
  SERVICE: our-places-web-app
  REGION: us-central1
  CARGO_TERM_COLOR: always
  LISTING_API_URL: ${{ vars.LISTING_API_URL }}
  GATEWAY_API_KEY: ${{ secrets.GATEWAY_API_KEY }}

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - web_app/**
      - common/**
      - .github/workflows/cicd_webapp.yml
      - Cargo.toml

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true
      - run: cargo audit --ignore RUSTSEC-2023-0071 --ignore RUSTSEC-2024-0436

  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path web_app/Cargo.toml

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run web_app tests
        run: cargo test --manifest-path web_app/Cargo.toml --verbose

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [audit, lint_check, test]
    
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
      
      - name: Set Release Flag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "RELEASE_FLAG=--release" >> $GITHUB_ENV
            echo "BUILD_OUTPUT=release" >> $GITHUB_ENV
          else
            echo "RELEASE_FLAG=" >> $GITHUB_ENV
            echo "BUILD_OUTPUT=debug" >> $GITHUB_ENV
          fi

      - name: Build and Push Web App
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE }}:${{ github.sha }} -f web_app/Dockerfile.web_app .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE }}:${{ github.sha }}
      
      - name: Deploy Web App
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE }}:${{ github.sha }}
          region: ${{ env.REGION }}
          env_vars: |
            LOG_FORMAT=json
            RUST_LOG=info
            LEPTOS_SITE_ADDR=0.0.0.0:8080
            LISTING_API_URL=${{ env.LISTING_API_URL }}
            GATEWAY_API_KEY=${{ env.GATEWAY_API_KEY }}
          flags: '--allow-unauthenticated --max-instances=1 --memory=256Mi --quiet'