name: Rust - test app_api

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./app_api
      run: cargo build --verbose
    - name: Run API tests
      working-directory: ./app_api
      run: cargo test --verbose

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Cloud SDK
    - uses: google-github-actions/setup-gcloud@v0.2.0
    - with:
        project_id: ${{ secrets.gcp_project }}
        service_account_key: ${{ secrets.gcp_credentials }}
        export_default_credentials: true